paths:
  /api/products/:
    get:
      summary : Gets all products
      tags: 
        - Products
      security:
        - cookieAuth: []
      responses:
        "200":
          description: The products were obtained successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: Internal Server Error
    post:
      summary: Create product
      tags: 
        - Products
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/updateProduct"  
      responses:
        "200":
          description: Product created successfully 
        "500":
          description: Internal Server Error
  /api/products/{pid}:
    get:
      summary : Search by id a product
      tags: 
        - Products
      security:
        - cookieAuth: []
      parameters:
      - name: pid
        in: path
        required: true
        description: Id of the product to request
        schema:
          $type: String
      responses:
        "200":
          description: The product was found successfully
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
    put:
      summary: Update fields of a product passed by id
      tags:
        - Products
      security:
        - cookieAuth: []
      parameters:
        - name: pid
          in: path
          required: true
          description: Id of the product to request
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/updateProduct"  
      responses:
        "200":
          description: The product was successfully updated
        "500":
          description: Internal Server Error
    delete:
      summary: Delete a product by its id
      tags:
        - Products
      security:
        - cookieAuth: []
      parameters:
      - name: pid
        in: path
        required: true
        description: Id of the product to request
        schema:
          $type: String
      responses:
        "200":
          description: The product was deleted correctly
        "500":
          description: Internal Server Error

components:
  schemas:
    Product: 
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id automatically generated by mongoDB
        title:
          type: String
          description: Product name is user generated
        description: 
          type: String
          description: The product description is generated by the user
        price:
          type: Number
          description: The price of the product is generated by the user
        thumbnails:
          type: String
          description: Product images are user generated
        code:
          type: String
          description: The product code is generated by the uuid library
        stock:
          type: Number
          description: The stock of the product is generated by the user
        owner:
          type: String
          description: The owner is generated by the user who created that product